s4u/pgp-keys-map

pom.xml
resources/pgp-keys-map.list

Keys for verifyPluginDependencies

---

pom.xml

project doesn't have site - so skip publishing

skip scmpublish

---

pom.xml

https://github.com/s4u/parent/releases/tag/v2.10.0

bump parent from 2.9.0 to 2.10.0

---

pom.xml

https://github.com/s4u/pgpverify-maven-plugin/releases/tag/v1.12.0

Bump pgpverify-maven-plugin from 1.11.0 to 1.12.0

---

resources/pgp-keys-map.list

connected with: https://github.com/codehaus-plexus/plexus-archiver/issues/175

new key for org.codehaus

---

pom.xml

https://github.com/s4u/pgpverify-maven-plugin/releases/tag/v1.13.0

Bump pgpverify-maven-plugin from 1.12.0 to 1.13.0

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

com.aoapps
com.aoapps.platform (will publish first artifacts soon)
com.aoindustries
com.pragmatickm
com.semanticcms

new key for groupIds published to Central Repository:

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

new key for com.newmediaworks

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This is the only artifact for groupId "net.sourceforge.barbecue".

noSig for net.sourceforge.barbecue:barbecue:1.5-beta1

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This is the only artifact for groupId "org.ostermiller".

noSig for org.ostermiller:utils:1.07.00

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This is the only artifact for groupId "informa".

noSig for informa:informa:0.6.0

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

noSig for jgraph

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

noSig for ant-contrib

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "yWorks GmbH <yguard@yworks.com>"

new key for com.yworks

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "dnsjava <dev@dnsjava.org>"

new key for dnsjava:dnsjava

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

The new signature is seen on Tomcat 7 builds and resolves to
"Violeta Georgieva Georgieva (CODE SIGNING KEY) <violetagg@apache.org>".

new key for org.apache.tomcat.*

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "LibreOffice Build Team (CODE SIGNING KEY) <build@documentfoundation.org>"

new key for org.libreoffice

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Josh Cain (always reforming.  always being reformed.) <hack@semper.reformanda.io>",
which has an email domain matching groupId.

new key for io.reformanda.semper

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Deanna <deannagarcia@google.com>"

new key for com.google.protobuf:protobuf-java

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "MySQL Release Engineering <mysql-build@oss.oracle.com>", which matches the documentation at
https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-verify-package.html

new key for mysql:mysql-connector-java

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This signature is listed as "ASF ID: veithen" at https://people.apache.org/keys/group/axis.asc

new key for org.apache.axis2

---

resources/pgp-keys-map.list

Signature resolves to "David Saff <david@saff.net>", which matches the JUnit team list at
https://junit.org/junit4/team-list.html

Additional key for junit

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Hiram Chirino <hiram@hiramchirino.com>".
Hiram Chirino is listed as a committer on several Apache projects at
https://people.apache.org/phonebook.html?uid=chirino
Hiram Chirino is listed as a developer on a related bundle artifact:
https://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.xalan/2.7.1_3
Following the parent projects, Hiram Chirino is found listed in "servicemix-pom":
https://repo1.maven.org/maven2/org/apache/servicemix/servicemix-pom/3/servicemix-pom-3.pom

new key for xalan

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This signature is listed as "ASF ID: lehmi" at https://people.apache.org/keys/group/pdfbox.asc

new key for org.apache.pdfbox

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Dave Cramer (As of July 18/2018) <davecramer@gmail.com>"
Dave Cramer is the verified committer on recent commits on the GitHub project:
https://github.com/pgjdbc/pgjdbc/commit/2f39510765a0f9ef803a1765b2f063b11fb82be2
The GitHub verification is with a different, older PGP key, however.

new key for org.postgresql:postgresql

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "David Blevins <dblevins@apache.org>".
David Blevins is listed with "Auth group membership" to "jcp-axis-nda" at https://people.apache.org/phonebook.html?uid=dblevins

new key for org.apache.axis

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

This signature is listed as "ASF ID: ggregory" at https://people.apache.org/keys/group/httpcomponents.asc

Additional key for org.apache.httpcomponents

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "TMate Software <support@tmatesoft.com>"

new key for org.tmatesoft and related artifacts signed by same key

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

The signature resolves to "Olivier Lamy <olamy@apache.org>" and is already in the mapping several times.

new key for com.google.code.maven-scm-provider-svnjava

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

The signature 00ECB4C4ED5885AC resolves to many addresses, including "Mirko Friedenhagen <mfriedenhagen@codehaus.org>".

new key for org.codehaus.mojo:buildnumber-maven-plugin

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

All artifacts are from around the years 2005-2006,
and confirmed none are signed.

noSig for jalopy

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signatures resolve to \"Benoit Tellier <btellier@apache.org>\" and \"Norman Maurer <norman@apache.org>\".
Both are listed as project members at https://people.apache.org/committers-by-project.html#james

new keys for org.apache.james

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Cezar Cristian Andrei <cezar@apache.org>".
Person is listed at https://people.apache.org/phonebook.html?uid=cezar
but unable to verify signature or project membership.

new key for org.apache.xmlbeans:*:2.6.0

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature is "ASF ID: chtompki" at https://people.apache.org/keys/committer/chtompki

new noSig and key for commons-fileupload

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature is "ASF ID: ay" at https://people.apache.org/keys/committer/ay

Refined noSig and new key for wsdl4j

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature is "ASF ID: veithen" at https://people.apache.org/keys/committer/veithen

new key for org.apache.woden

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Tatu Saloranta (Home Mini-Mac) <tatu.saloranta@iki.fi>".

New key for org.codehaus.woodstox:woodstox-core-asl

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

The signature is listed as "ASF ID: dkulp" at https://people.apache.org/keys/committer/dkulp

new key for org.apache.neethi

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature is "ASF ID: coheigea" at https://people.apache.org/keys/committer/coheigea

Additional key for org.apache.ws.xmlschema

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Martin Grebac (snajper) <martin.grebac@oracle.com>".

Additional key for com.sun.xml.ws

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signatures resolve to:
1) "ASF ID: veithen" at https://people.apache.org/keys/committer/veithen
2) "ASF ID: robertlazarski" at https://people.apache.org/keys/committer/robertlazarski

new keys for org.apache.ws.commons.axiom

---

pom.xml

It Is done in verification matrix

Skip verification on deploy

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signatures resolve to:
1) "Mark Struberg (Apache) <struberg@apache.org>", listed as "ASF ID: struberg"
at https://people.apache.org/keys/committer/struberg
2) "Guillaume Nodet <gnodet@apache.org>", listed as "ASF ID: gnodet"
at https://people.apache.org/keys/committer/gnodet

Additional keys for org.apache.xbean

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signatures resolve to:
1) "Jason Dillon (Maven Codesign) <jason@planet57.com>"
2) "Jason Dillon (Maven Codesign Key) <jason@planet57.com>"
Jason Dillon's LinkedIn profile contains "Groovy Committer" and
"Creator of GMaven (v1 and v2)": https://www.linkedin.com/in/jasondillon

new keys for org.codehaus.gmaven.* and related dependencies

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Robert Lazarski (CODE SIGNING KEY) <robertlazarski@gmail.com>".
Signature matches that listed for "ASF ID: robertlazarski" at https://people.apache.org/keys/committer/robertlazarski
Robert Lazarski is listed as a committer for "axis" at https://people.apache.org/committer-index.html
This should resolve the issue in dependabot PR #285

new key for axis2-1.8.0

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

New signature resolves to "Benedikt Ritter (CODE SIGNING KEY) <britter@apache.org>".
Signature is listed as "ASF ID: britter" at https://people.apache.org/keys/committer/britter

additional "noSig" and key for commons-cli

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Versions 2.3.19 and before are unsigned.
Version 2.3.27-incubating is signed by "Woonsan Ko <woonsan@apache.org>".
All other versions are signed by "Daniel Dekany <ddekany@apache.org>".

new key for org.freemarker

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Lukasz Lenart (Signing Apache Distributions) <lukaszlenart@apache.org>".
Key matches "ASF ID: lukaszlenart" at https://people.apache.org/keys/committer/lukaszlenart
This contributor is listed as a member of "Apache Struts" project: https://people.apache.org/phonebook.html?pmc=struts

new key for Struts 2

---

org-apache-maven-plugins-test/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Andreas Dangel <andreas.dangel@adangel.org>".
Key matches "ASF ID: adangel" at https://people.apache.org/keys/committer/adangel
"adangel" is listed as a member of "maven" project at https://people.apache.org/committers-by-project.html#maven

Additional key for org.apache.maven.*

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Alan Malloy <amalloy@google.com>".

additional key for error_prone_annotations

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Emmanuel Lecharny (CODE SIGNING KEY) <elecharny@apache.org>".
Mr. Lecharny is listed as a contributor on the "mina" project at https://people.apache.org/committer-index.html
The signature matches that listed as "ASF ID: elecharny" at https://people.apache.org/keys/committer/elecharny

new key for org.apache.mina

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Jason Hunter <jhunter@servlets.com>"
Jason Hunter is listed at the JDOM project founder at http://jdom.org/credits/index.html

Additional key for org.jdom

---

org-apache-maven-plugins-test/pom.xml
pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Gregory Brail (Rhino Automated Builds) <greg+rhino@brail.org>".
Gregory is the creator of the related GitHub release:
https://github.com/mozilla/rhino/releases/tag/Rhino1_7_14_Release
Gregory is a member of the "mozilla" organization on GitHub:
https://github.com/orgs/mozilla/people?query=gbrail
This extends and resolves the build error of PR #551

New key for org.mozilla:rhino

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Liam Miller-Cushon (Error Prone releases) <cushon@google.com>".
Liam is an active committer on several Google projects:       
https://github.com/cushon
https://github.com/google/error-prone/commits?author=cushon
This extends and resolves the build error of PR #577

Additional key for com.google.googlejavaformat

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Terence Parr <parrt@antlr.org>".
Terence Parr is the lead of the ANTLR project as described at https://www.antlr.org/
His GitHub user is also the one to release antlr-3.5.3:
https://github.com/antlr/antlr3/releases/tag/3.5.3
https://github.com/parrt
This is a new key that was generated 2022-04-02.
This builds on PR #639 and resolves its build error.
This will also fix PRs #637 #638 #642 and #644 once rebased.

Additional key for org.antlr

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Josh Haberman <haberman@google.com>".
GitHub user "haberman" authored the associated release:
https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.1
https://github.com/haberman
This builds on PR #668 and resolves its build error.

Additional key for com.google.protobuf:protobuf-java

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Fabian Stäber <fabian@fstab.de>".
Related GitHub user "fstab" published the corresponding GitHub release:
https://github.com/prometheus/client_java/releases/tag/parent-0.15.0
https://github.com/fstab

new key for io.prometheus

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Spring Buildmaster <buildmaster@springframework.org>".
This key has a long history and is already in the map for other Spring-related projects.

new key for io.projectreactor.*

---

pom.xml

Updated to the current version of org.simplify4u:parent:2.16.0

Bumped to org.simplify4u:parent:2.16.0

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Download <download@jetbrains.com>".
This matches the key published at https://github.com/JetBrains/java-annotations/blob/master/KEYS

Additional key for org.jetbrains:annotations

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Spring Buildmaster <buildmaster@springframework.org>".
This key has a long history and is already in the map for other Spring-related projects.

new key for io.micrometer.*

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Add key for org.eclipse.packager

---

resources/pgp-keys-map.list

https://github.com/qos-ch/slf4j/blob/master/SECURITY.md

Add new key for org.slf4j

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Simone Tripodi (simonetripodi) <simonetripodi@apache.org>".
This is the same key as already in the map for commons-digester:commons-digester

new key for commons-digester3

---

resources/pgp-keys-map.list

Revert "Allow not found key for org.codehaus.plexus:plexus-archiver:4.5.0"

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Signature resolves to "Matt Sicker <mattsicker@apache.org>".
This key is listed as "ASF ID: mattsicker" at https://people.apache.org/keys/committer/mattsicker
mattsicker is listed as a contributor to "commons" at https://people.apache.org/phonebook.html?unix=commons

new key for commons-compress

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Add Konrad's key to allow signing org.codehaus.plexus group

---

resources/pgp-keys-map.list

Reference: https://github.com/qos-ch/logback/blob/master/SECURITY.md

Add new key for ch.qos.logback

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Replacement for 
- https://github.com/s4u/pgp-keys-map/pull/1346

Include spockframework keyId

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

- https://github.com/s4u/pgp-keys-map/pull/1739
- https://github.com/s4u/pgp-keys-map/pull/1740

Add key used to sign org.glassfish.expressly

---

pgp-keys-map-test2/pom.xml
resources/pgp-keys-map.list

New key is countersigned by 0x9FA2B7299F51E543.

Add key for jakarta.validation

---

pgp-keys-map-test2/pom.xml
resources/pgp-keys-map.list

Present in https://www.apache.org/dist/creadur/KEYS

Add key for org.apache.rat

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

See https://github.com/smooks/smooks/security/advisories/GHSA-7wcp-7vh5-mpc8.

Add keys for Smooks

---

resources/pgp-keys-map.list

New key for com.github.javaparser

---

resources/pgp-keys-map.list

New key for org.mortbay.jasper

---

resources/pgp-keys-map.list

New key was used to sign https://repo.maven.apache.org/maven2/org/yaml/snakeyaml/2.3/

Add new key for org.yaml

---

resources/pgp-keys-map.list

https://lists.apache.org/thread/c1pkzmd5kn08r8wdr9tbc5ygdg0o663j

Add new key for velocity

---

resources/pgp-keys-map.list

- This should help with #2684
- https://www.mail-archive.com/dev%40felix.apache.org/msg56659.html
- https://www.mail-archive.com/dev%40felix.apache.org/msg56751.html

Add new key for org.apache.felix

---

resources/pgp-keys-map.list

Mark revoked keys

---

pgp-keys-map-test2/pom.xml
resources/pgp-keys-map.list

Add key for ActiveMQ

---

pgp-keys-map-test2/pom.xml
resources/pgp-keys-map.list

Add keys for OpenMQ and its dependencies

---

pgp-keys-map-test1/pom.xml
resources/pgp-keys-map.list

Add keys for org.apache.lucene

---

resources/pgp-keys-map.list

This is maintained by Eclipse Foundation and is signed by 0x9FA2B7299F51E543.

Add key for Jakarta WebSocket

---

resources/pgp-keys-map.list

- https://github.com/s4u/pgp-keys-map/pull/2973#discussion_r2119357721

Fix jfreechart keys list

---

resources/pgp-keys-map.list

New m-pmd-p pulls newer PMD. It triggered this change on my side.

New PMD key
