- pgp-keys-map-test1/pom.xml
- pgp-keys-map-test3/pom.xml
- pom.xml
- resources/pgp-keys-map.list
- Upgraded some dependency versions.
- Defined versions using fixed-version notation to avoid accidental influencing by dependencies pull in through the dependency tree.
- Added new entries in keys map, and added corresponding dependencies and build plug-ins in `pgp-keys-map-test1`.
- Added version distinction for `apache-commons:commons-lang3`. We might want to generalize further in the future, although I cannot be sure if this is actually necessary right now.
> Extend keys map

- resources/pgp-keys-map.list
- `spring-framework` from version 5.3.1
- `spring-boot` from version 2.4.0 
use new key for signing artifacts, now key: `0x8756c4f765c9ac3cb6b85d62379ce192d401ab61` is used.
As we see it is key bellong to `Bintray` and key id is consistent with the description 
https://www.jfrog.com/confluence/display/BT/Managing+Uploaded+Content#ManagingUploadedContent-SigningwiththeBintrayKey
> New key for org.springframework

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
All artifacts for groupId "slide" are from around 2005, and none
of them have any signatures.
> noSig for slide

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This is the only artifact for groupId "de.zeigermann.xml", and is
also from the year 2005 without any signatures.
> noSig for de.zeigermann.xml:xml-im-exporter:1.1

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
All artifacts for groupId "taglibs" are from around 2005, and none
of them have any signatures.
> noSig for taglibs

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This is the only artifactId in groupId "eu.medsea.mimeutil".
We specified a version range matching the published artifacts.
If a newer version is ever released, we would expect a signature.
> noSig for eu.medsea.mimeutil:mime-util

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
In version 1.3.03, only pom is signed.
In version 1.4.01, all artifacts are signed.
In all other versions, nothing is signed.
> Added signatures for the subset of xml-apis that are signed

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Key resolves to "Jason Robert Dillon (CODE SIGNING KEY) <jason@planet57.com>".
There is a Jason Dillon LinkedIn profile that shows works at Sonatype:
https://www.linkedin.com/in/jasondillon
---
Please note: There is an exclusion in the test that will not be required if pull request #187 is merged before this.  I will be happy to rebase and remove this exclusion if #187 goes in first.
> Added key for more org.sonatype

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Eclipse Project for JTA <jta-dev@eclipse.org>",
which is consistent with Java EE being moved to Eclipse.
> new key for jakarta.transaction

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
4DB7BC57DFDBCEA4 resolves to "Timothy Wall <twall@users.sf.net>".
Timothy Wall is associated with related GitHub projects:
https://github.com/java-native-access/jna#community-and-support
15C71C0A4E0B8EDD resolves to "Matthias Bläsing <mblaesing@doppel-helix.eu>".
Matthias Bläsing is listed as a developer:
https://github.com/java-native-access/jna/blob/d367f0220be55b5638b3d324473ef0a7e654d83c/pom-jna-platform.xml#L53
> Additional keys for net.java.dev.jna

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Lucee <info@lucee.org>"
These are a one-off repackaging of the latest version of Xalan.  Unlike the
original packaging, they do not contain any split-packages, and may thus be used
as Java 9+ JPMS filename-based automatic modules.
> new key for org.lucee:xalan[-serializer]

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Leo Bayer <lfbayer@gmail.com>"
Leo Bayer is also the committer on the related GitHub release:
https://github.com/brettwooldridge/SparseBitSet/releases/tag/SparseBitSet-1.2
Leo Bayer is also listed as a developer on other com.zaxxer projects, but I
do not want to assume them as a signer beyond SparseBitSet:
https://search.maven.org/artifact/com.zaxxer/sansorm
> new key for com.zaxxer:SparseBitSet

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This signature is already in the map for other Oracle-signed artifacts.
> new key for javax.xml.rpc

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This signature is included in tomcat KEYS file at https://github.com/apache/tomcat/blob/85ff05f396ffdb19a2df69123f51f8c784e95ee0/KEYS#L593
> new key for org.apache.taglibs

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Karl Schaefer (SwingX Project Owner) <kschaefe@java.net>"
> new key for org.swinglabs.swingx

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Simon Steiner (CODE SIGNING KEY) <ssteiner@apache.org>"
Simon Steiner is listed as a committer on the xmlgraphics project:
https://people.apache.org/phonebook.html?uid=ssteiner
However, this signature is not found at https://people.apache.org/keys/group/xmlgraphics.asc
> Additional key for org.apache.xmlgraphics

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The signature matches recent verified commits on the project, such as
https://github.com/rototor/pdfbox-graphics2d/commit/b67d59e8876c817690a330912ea84d5a0b0362bb
> new key for de.rototor.pdfbox

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
All artifacts and versions that do not have signatures are specifically added "noSig".
All other artifacts have PGP signatures.
The existing signature 6B1B008864323B92 resolves to "Terence Parr (ANTLR Project Lead) <parrt@antlr.org>".
The first new signature 6EB9DE4D7E01B1E1 resolves to "Terence Parr (ANTLR Author) <parrt@antlr.org>".
The other new signature 82B5574242C20D6F resolves to "Sam Harwell <sam@tunnelvisionlabs.com>", whose GitHub projects are antlr-related: https://github.com/sharwell
> new keys and more specific "noSig" for org.antlr

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Evan Ward <evanward@apache.org>".
Evan Ward is listed as a committer on "commons":
https://people.apache.org/phonebook.html?uid=evanward
However, because this signature is not specifically listed, we are only applying to the "commons-math3" artifactId:
https://people.apache.org/keys/group/commons.asc
> new key for org.apache.commons:commons-math3

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Ralph Schaer <ralphschaer@gmail.com>".
Ralph Schaer is listed as a developer in the project pom.xml:
https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj-4.6.1.pom
Ralph Schaer as a developer is also referenced in Eclipse bug #484004:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004
> new key for org.eclipse.jdt.core.compiler

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This signature is listed as "ASF ID: kiwiwings" at https://people.apache.org/keys/group/poi.asc
org.apache.xmlbeans:xmlbeans has been part of POI since version 3.0.0, while older versions and other artifacts do not seem as closely related to POI.
We have only added the signature for the latest release of org.apache.xmlbeans:xmlbeans, signatures for older versions can be added on an as-needed basis.
> new key for org.apache.poi and org.apache.xmlbeans:xmlbeans

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Olivier Lamy <olamy@apache.org>".
Olivier Lamy is listed as a committer on many projects, including "tomcat":
https://people.apache.org/phonebook.html?uid=olamy
However, because this signature is not specifically listed, we are only applying to the "org.apache.tomcat.maven" groupId:
https://people.apache.org/keys/group/tomcat.asc
> new key for org.apache.tomcat.maven

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature 2C026998703FFA67 resolves to "Eclipse Project for Expression Language <el-dev@eclipse.org>".
Signature 260E672C0D78E9B0 resolves to "Eclipse Project for Servlet <servlet-dev@eclipse.org>".
Signature 296863EC7506AB74 resolves to "Eclipse Project for JSTL <jstl-dev@eclipse.org>".
> new keys for Jakarta JSTL

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
I am unable to find any meaningful information to verify the B7C3B43D18EAA8B7 signature.  However, this mapping entry will still ensure future releases are signed by the same key as the first and only release.
> new key for org.codehaus.mojo:properties-maven-plugin

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Eclipse JDT Project <jdt-dev@eclipse.org>".
There are many artifacts in the "org.eclipse.jdt" groupId.  We have only included the artifactId we require, and we do not want to assume the signatures of other artifacts.
> new key for org.eclipse.jdt:ecj

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Versions 1.7.1 and below have a signature that resolves to "Rei Odaira (lz4-java maintainer) <Rei.Odaira@gmail.com>".
Versions 1.8.0, the current latest release, has a signature that is not found in any of the public keyservers so is marked "noKey".
> new keys for org.lz4

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "hynnet.com (hynnet.com) <hynnet@hynnet.com>".
There are many artifacts in the "com.hynnet" groupId.  We have only included the artifactId we require, and we do not want to assume the signatures of other artifacts.
> new key for com.hynnet:jacob

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The signature does not provide any name or email address.
However, I do find the project at GitHub at https://github.com/virtuald/curvesapi
This is the first and only artifactId within com.github.virtuald published, so we have added the key to verify future artifacts are signed with the same key.
> new key for com.github.virtuald

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This signature is listed as "ASF ID: coheigea" at https://people.apache.org/keys/group/santuario.asc
> new key for org.apache.santuario

- resources/pgp-keys-map.list
This fixes the ordering of keys in PR #217: https://github.com/s4u/pgp-keys-map/pull/217
---
Signature resolves to "Evan Ward <evanward@apache.org>".
Evan Ward is listed as a committer on "commons":
https://people.apache.org/phonebook.html?uid=evanward
However, because this signature is not specifically listed, we are only applying to the "commons-math3" artifactId:
https://people.apache.org/keys/group/commons.asc
> Fixed sorting of keys from PR #217

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature 37B0A85F5CE89B0C resolves to "Jan Bartel <janb@webtide.com>", who is listed as a project lead for Jetty:
https://projects.eclipse.org/content/jan-bartel-project-lead-jetty-servlet-engine-and-http-server
Signature 873A8E86B4372146 resolves to "Olivier Lamy <olamy@apache.org>", who is already in the key map for several projects.
> new keys for Jetty-related artifacts

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The signature does not resolve to any name or email address, so we have only added the key to this specific artifactId
> new key for com.google.errorprone:error_prone_annotations

- pgp-keys-map-test1/pom.xml
We will be relocating noc-monitor-portmon to a different groupId,
while javatator will stay at com.aoindustries.
> Changed test to artifact that will stay at "com.aoindustries"

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Both signatures are listed as "ASF ID: carnold" at https://people.apache.org/keys/committer/carnold
For version 1.2.15, the pom artifact is not signed so marked "noSig".
The other artifacts are signed.
> new keys and noSig for log4j:log4j:1.2.15-1.2.16

- resources/pgp-keys-map.list
Signature resolves to "Martin Grebac (snajper) <martin.grebac@oracle.com>".
This signature is observed on at least javax.xml.bind:jaxb-api:2.2.6
> Additional key for javax.xml.bind

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Martin Grebac <martin.grebac@oracle.com>", notably it is a different signature than used for javax.xml.bind.
> More precisely mapped noSig and added key for com.sun.xml.bind

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Reviewed all artifacts in the org.apache.geronimo.specs groupId, adding all necessary noSig.
Added two new keys needed by our builds:
1) Matt Hogstrom <hogstrom@apache.org> is "ASF ID: hogstrom" at https://people.apache.org/keys/committer/hogstrom
2) Guillaume Nodet <gnodet@apache.org> is "ASF ID: gnodet" at https://people.apache.org/keys/committer/gnodet
> Thoroughly mapped noSig and new keys for org.apache.geronimo.specs

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Older versions of com.thoughtworks.qdox:qdox, from 1.12 and before, are not signed.
> noSig for com.thoughtworks.qdox <= 1.12

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
All artifacts in com.servlets groupId are unsigned.
> noSig for com.servlets

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Mapped all artifacts in "javax.transaction" groupId.
New keys resolve to:
1) java_re <GF_RELEASE_WW@oracle.com>
2) Stephen Felts <stephen.felts@oracle.com>
3) Maven Central Java.net import (Used to sign artifacts imported from Java.net repos) <repository@sonatype.com>
> new keys for javax.transaction

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Don Corley (Primary gpg key) <don@donandann.com>".
GitHub user "doncorley" is the primary contributor to jibx-related projects:
https://github.com/jibx/core/graphs/contributors
> new key for org.jibx

- resources/pgp-keys-map.list
Signatures resolve to:
1) "PJ Fanning <fanningpj@yahoo.com>" - Unable to specifically verify signature
2) "Greg Woolsey <gwoolsey@apache.org>" - Matches "ASF ID: gwoolsey" at https://people.apache.org/keys/committer/gwoolsey
Both people are listed as contributors on the "poi" project at https://people.apache.org/phonebook.html?unix=poi
> new keys for org.apache.xmlbeans:xmlbeans:[3.0.0,3.1.0]

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Liam Miller-Cushon <cushon@google.com>".
This signature is already present in the map for the "com.google.errorprone" groupId.
> new key for com.google.googlejavaformat

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Versions before 1.0 are unsigned.
Version 1.0 signed by "Douglas Campos <qmx@qmx.me>", and this key was revoked 2012-04-24.
Newer versions are signed by:
1) "Jason Dillon (Maven Codesign) <jason@planet57.com>" - This key is already in the map for several different artifacts.
2) "Guillaume Nodet <gnodet@apache.org>" - This key is also already in the map for several different artifacts.
> Added keys for jline

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Key resolves to "Jason Robert Dillon (CODE SIGNING KEY) <jason@planet57.com>", and is already in the map for several different artifacts.
> Added key for org.codehaus.gmaven

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Added noSig for older "javassist" groupId.
Found a couple versions noSig for newer "org.javassist" groupId.
Added keys for newer "org.javassist" groupId:
1) "Andrew Dinn (JBoss Developer) <adinn@redhat.com>"
2) "Shigeru Chiba (Javassist Developer) <chiba@javassist.org>"
> new keys for javassist

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Versions prior to 3.0 are unsigned.
Version 3.0 is signed by "Lukasz Lenart <lukaszlenart@apache.org>".
Version 3.1.12 is signed by "Lukasz Lenart <lukasz@softwaremill.com>".
All other versions are signed by "Lukasz Lenart (Signing Apache Distributions) <lukaszlenart@apache.org>".
> new keys for ognl

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Bo Yang <teboring@google.com>".
Although a different GPG key, this matches the identity of the 3.18.0 release "TeBoring":
https://github.com/protocolbuffers/protobuf/releases/tag/v3.18.0
https://github.com/TeBoring
> Additional key for protobuf-java

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Thoroughly reviewed all artifacts in the javax.el groupId, included all necessary keys in PGP keys map.
1) Older javax.el:el-api artifacts:
Signature resolves to "Maven Central Java.net import (Used to sign artifacts imported from Java.net repos) <repository@sonatype.com>".
This same signature is already in the map for numerous artifacts of a similar vintage.
2) Oldest javax.el:javax.el-api artifact:
Signature resolves to "Jane Young <jane.young@oracle.com>".
3) Majority of the javax.el:javax.el-api artifacts:
Signature resolves to "java_re <GF_RELEASE_WW@oracle.com>".
This same signature is already in the map for many recent Java EE artifacts.
We bounded the range of this key, since we do not expect any more releases from Oracle due to the Java EE projects being moved to Jakarta EE under …
> new keys for javax.el

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This is to resolve the build failure of 85ae9af16f79b951b262164e9869f5dbf0d0e731
com.github.spotbugs
---
Signature resolves to "Jeremy Landis (hazendaz) <jeremylandis@hotmail.com>".
This matches the GitHub identity "hazendaz" of the commit associated with the most recent release:
https://github.com/spotbugs/spotbugs-maven-plugin/commit/741f662a0d32ca1d4307d5bf47f75424893104ff
The commits are not signed, however, so we cannot compare any specific PGP keys.
com.github.javaparser dependency
---
Signature resolves to "Roger Howell <MysterAitch@users.noreply.github.com>".
This matches the GitHub identity "MysterAitch" of the commit associated with the most recent release:
https://github.com/javaparser/javaparser/commit/67d7edf70b7cb03a2c717b74b5ed23c640de22f3
The commits are not signed, …
> Additional keys for com.github.spotbugs and related dependencies

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Thoroughly mapped all artifacts and versions in the javax.servlet.jsp groupId.
The two signatures are the same as seen on other Java EE artifacts.
> new keys for javax.servlet.jsp

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Most older artifacts are "noSig", with a one-off exception:
servlet-api:3.0-alpha-1 has the same signature as many other older Java EE artifacts.
> More thorough mapping older artifacts in "javax.servlet" groupId

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The older artifacts use the same signing key as many other Java EE artifacts.
The signature of the newer versions resolves to "Jersey Robot <jerseyrobot@java.net>".
This key is also already in the map for "com.sun.jersey".
> new keys for javax.websocket

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Tamás Cservenák <tamas@cservenak.net>".
This matches the GitHub identity "cstamas" of the commit associated with the most recent release:
https://github.com/codehaus-plexus/plexus-sec-dispatcher/commit/0bab9aa096c411973ce3d48771a8fe735cafd917
The commits are not signed, however, so we cannot compare any specific PGP keys.
> new key for org.codehaus.plexus:plexus-sec-dispatcher

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
This is the same signature as already in the map for many other Java EE artifacts.
This resolves the build error in #362
> new key for javax.annotation

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
poi 5.1.0 has the same key as the recent release of the related xmlbeans project,
which is also the same key used for previous xmlbeans releases.
> Added mapping for poi-5.1.0

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Stefan Seelmann (CODE SIGNING KEY) <seelmann@apache.org>".
Mr. Seelmann is listed as a contributor to the "directory" project at https://people.apache.org/committer-index.html
This signing key does not match that listed at https://people.apache.org/keys/committer/seelmann
I have sent an email to Mr. Seelmann, asking him to verify this key is his and to also update his keys listed at people.apache.org
> new key for org.apache.directory.api

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Jean-Baptiste Onofré <jbonofre@apache.org>"
jbonofre@apache.org is listed as a contributor to the "servicemix" project at https://people.apache.org/committer-index.html
There is no specific key listed on people.apache.org, but this key matches that already in the map for the "felix" project, for which they are also listed as a contributor.
> new key for org.apache.servicemix.bundles

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
These are the keys (or lack thereof) for the current dependencies of the
Dropwizard project.
I haven't verified their authenticity. Caveat emptor.
> Add keys for dependencies of Dropwizard

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Matthew Sicker (Signing Key) <mattsicker@apache.org>"
This signatures matches that listed at https://people.apache.org/keys/committer/mattsicker for ASF ID "mattsicker".
mattsicker is listed on the roster of the "logging" project at https://people.apache.org/phonebook.html?unix=logging
> Additional key for org.apache.logging.log4j

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Versions of org.codehaus.groovy:groovy 2.2.1 and below are not signed.
This resolves the dependency problem in #487  Please accept this PR then rebase #487
> Added "noSig" for older org.codehaus.groovy:groovy

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Xisco Fauli <xiscofauli@libreoffice.org>"
Xisco Fauli is listed under libreoffice professional support at https://www.libreoffice.org/get-help/professional-support/
This PR includes the commit from #493 and resolves the build failure.  If you would prefer a single commit independent of #493, we can rebase.
> Additional key for org.libreoffice

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature matches the new key for versions >= 8.0.28 documented at https://dev.mysql.com/doc/refman/8.0/en/checking-gpg-signature.html
This builds upon and resolves the build error of PR #516
> New key for mysql-connector-java >= 8.0.28

- org-apache-maven-plugins-test/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Slawomir Jaranowski <sjaranowski@apache.org>", and matches the key for "ASF ID: sjaranowski" at https://people.apache.org/keys/committer/sjaranowski
sjaranowski is listed as a contributor to "maven" at https://people.apache.org/phonebook.html?unix=maven
This builds on and resolves #518
> Additional key for org.apache.maven.*

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Key exists in keys.openpgp.org but contains no user ID.  This basically means this commit blindly accepts this signing key without any meaningful identity verification.
I was unable to find any relevant GitHub for the project, only older versions and forks.
I do not find any signing key information on the download page at https://svnkit.com/download.php
I do not find any signing key information at the SVN tag at https://svn.svnkit.com/repos/svnkit/tags/1.10.4/
This resolves PR #528
> Additional key for org.tmatesoft.*

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
> Add some updated keys and make some noSig rules more generic

- org-apache-maven-plugins-test/pom.xml
- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Torsten Curdt (Code Signing Key) <tcurdt@vafer.org>"
1) This is a different signing key than Mr. Curdt uses for Apache projects:
https://people.apache.org/keys/committer/tcurdt
2) Cannot find any signing keys on his GitHub project or profile:
https://github.com/tcurdt/jdependency
https://github.com/tcurdt
Cannot specifically validate this PGP key, but the unverified identity does match the project well.
This builds on PR #609 and resolves its build error.
> Additional key and new test for org.vafer

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "mkruskal <mkruskal@google.com>"
GitHub user "mkruskal-google" has recently published the next pre-release of protobuf-java:
https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.1-rc1
https://github.com/mkruskal-google
The GitHub commits are not signed, however, so unable to find any specific PGP keys for comparison.
This builds on PR #626 and resolves its build error.
> Additional key for com.google.protobuf:protobuf-java

- org-codehaus-mojo-test/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Stefan Seifert <stefan.seifert@diva-e.com>"
GitHub user "stefanseifert" is the committer on the release's associate tag:
https://github.com/mojohaus/versions-maven-plugin/releases
https://github.com/mojohaus/versions-maven-plugin/tree/versions-maven-plugin-2.10.0
https://github.com/stefanseifert
None of the GitHub commits appear to be signed, however, so cannot specifically validate this PGP key.
The identity, as much as we can verify, does look correct for this project.
This builds on PR #593 and resolves its build error.
> new key for org.codehaus.mojo:versions-maven-plugin

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
net.i2p.crypto
---
Signature resolves to "str4d (Package signing) <str4d@mail.i2p>"
"str4d" is listed as a "Release Manager Alternates" at https://geti2p.net/en/contact
GitHub user "str4d" owns the repository related to this project:
https://github.com/str4d/ed25519-java/releases/tag/v0.3.0
org.apache.sshd
---
Signature resolves to "Guillaume Nodet (CODE SIGNING KEY) <gnodet@gmail.com>"
This is a different PGP key than that listed for ASF ID "gnodet" at https://people.apache.org/keys/committer/gnodet
Guillaume is a member of many Apache projects, but it is unclear which project "org.apache.sshd" is part of:
https://people.apache.org/committer-index.html#gnodet
---
This builds on PR #614 and resolves its build error.
> new keys for dependencies of svnkit-1.10.5

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
info.picocli
---
Signature resolves to "Popma Remko <remkop@yahoo.com>"
GitHub user "remkop" owns the repository related to this project:
https://github.com/remkop/picocli/releases/tag/v4.6.3
org.reflections:reflections
---
Signature does not have any user ID:
`gpg: key F13D3E721D56BD54: new key but contains no user ID - skipped`
The release dates match between GitHub and Maven Central, which at least means it is likely the same person with access to both GitHub and Maven Central.
https://github.com/ronmamo/reflections/releases/tag/0.10.2
https://repo1.maven.org/maven2/org/reflections/reflections/0.10.2/
> new keys for dependencies of checkstyle-10.1

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Liam Miller-Cushon (Error Prone releases) <cushon@google.com>".
This key is also already in the map for groupId "com.google.googlejavaformat".
This builds on PR #651 and resolves its build error.
> Additional key for com.google.errorprone:error_prone_annotations

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Jean-Baptiste Onofré <jbonofre@apache.org>".
Listed as ASF ID "jbonofre", but no PGP keys given:
https://people.apache.org/committer-index.html
GitHub user "jbonofre" authored the associated release:
https://github.com/apache/geronimo-xbean/releases/tag/xbean-4.21
https://github.com/jbonofre
This builds on PR #654 and resolves its build error.
> Additional key for org.apache.xbean

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Changed keys map entry to use asterisk wildcard.
Added tests for httpclient5 and httpcore5.
No new PGP keys.
> httpcomponents 5 is released under multiple groupId

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Hidekatsu Izuno <hidekatsu.izuno@gmail.com>".
The related GitHub user "hidekatsu-izuno" published the associated GitHub release:
https://github.com/hidekatsu-izuno/nashorn-promise/releases/tag/v0.1.3
https://github.com/hidekatsu-izuno
> new key for net.arnx

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
First signature resolves to "Netty Project Bot <netty-project-bot@users.noreply.github.com>".
This is the GitHub user that published the associated release:
https://github.com/netty/netty/releases/tag/netty-4.1.76.Final
https://github.com/netty-project-bot
---
Second signature resolves to "Chris Vest (chrisvest on github, chvest on twitter) <mr.chrisvest@gmail.com>".
GitHub user "chrisvest" is a frequent committer on the project:
https://github.com/netty/netty/commits/4.1
https://github.com/chrisvest
---
Third signature resolves to "Norman Maurer <norman@apache.org>".
GitHub user "normanmaurer" is a frequent committer on the project:
https://github.com/netty/netty/commits/4.1
https://github.com/normanmaurer
> new keys for io.netty

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "abego Software GmbH, Germany (Key for Maven) <contact@abego.org>".
The related GitHub user "abego" published the associated GitHub release:
https://github.com/abego/treelayout/releases/tag/v1.0.3
https://github.com/abego
> new key for org.abego.treelayout

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
First signature resolves to "java_re <GF_RELEASE_WW@oracle.com>".
Second signature resolves to "EE4J Automated Build <tomas.kraus@oracle.com>".
Both keys are already in the map for several Java EE-related artifacts.
> new key for org.glassfish:javax.json

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Luke Hutchison <luke.hutch@gmail.com>".
The related GitHub user "lukehutch" published the associated GitHub release:
https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.146
https://github.com/lukehutch
> new key for io.github.classgraph

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Gil Tene <gil@azul.com>".
The related GitHub user "giltene" published the associated GitHub release:
https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.1.12
https://github.com/giltene
> new key for org.hdrhistogram

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Kotlin Release <kt-a@jetbrains.com>".
This matches the key documented at https://kotlinlang.org/docs/security.html
> new key for org.jetbrains.kotlin

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Viktor Klang <viktor.klang@gmail.com>".
Related GitHub user "viktorklang" published the associated GitHub release:
https://github.com/reactive-streams/reactive-streams-jvm/releases/tag/v1.0.3
https://github.com/viktorklang
> Additional key for org.reactivestreams

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Release Team <release@evolvedbinary.com>".
The GitHub user "hx235" created the associated GitHub release:
https://github.com/facebook/rocksdb/releases/tag/v7.1.2
https://github.com/hx235
I am unable to specifically connect this PGP to the GitHub identity or release.  However, it is worth noting the GitHub release and Maven Central artifacts have a matching date of 2022-04-20.
> new key for org.rocksdb

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Stefan Niederhauser <ich@nidi.guru>".
Related GitHub user "nidi3" published the associated GitHub release:
https://github.com/nidi3/graphviz-java/releases/tag/graphviz-java-parent-0.18.1
https://github.com/nidi3
PR #677 should go in before this one.
> new key for guru.nidi.*

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Oracle Maven Release <maven_release_grp@oracle.com>".
GitHub user "ezzarghili" authored the associated GitHub release:
https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.0.0.2
https://github.com/ezzarghili
GitHub user "ezzarghili" is a member of both related GitHub organizations:
https://github.com/oracle
https://github.com/graalvm
> new key for org.graalvm.*

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Gil Tene <gil@cloud7.com>".
The related GitHub user "giltene" published the associated GitHub release:
https://github.com/LatencyUtils/LatencyUtils/releases/tag/LatencyUtils-2.0.3
https://github.com/giltene
> new key for org.latencyutils

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "RSocket Admin <admin@rsocket.io>".
Unable to find any way to specifically validate this PGP key, however.
> new key for io.rsocket

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Aaron Gershman (Aaron Gershman at ModerneInc) <aaron@moderne.io>".
GitHub user "tkvangorder" created the associated GitHub release:
https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v4.22.2
https://github.com/tkvangorder
I am unable to specifically connect this PGP to the GitHub identity or release.  However, it is worth noting the GitHub release and Maven Central artifacts have a matching date of 2022-04-07.
> new key for org.openrewrite.*

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "BJ Hargrave (bintray.com osgi organization) <hargrave@us.ibm.com>".
GitHub user "bjhargrave" created the associated GitHub release:
https://github.com/osgi/osgi/releases/tag/8.0.0.1
https://github.com/bjhargrave
This PGP key is the same used for verified commits on the GitHub release tag.
> Additional key for org.osgi

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The PGP key does not have any user ID:
`gpg: key DFE102108BF9381F: new key but contains no user ID - skipped`
It is worth noting that this same PGP key has been used for all of the recent releases.
The GitHub user "Hibernate-CI" published the associated release:
https://github.com/hibernate/hibernate-validator/releases/tag/8.0.0.Alpha3
https://github.com/Hibernate-CI
> new key for org.hibernate.validator

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "BJ Hargrave (Open Source Development) <bj@hargrave.dev>".
GitHub user "bjhargrave" created the associated GitHub release:
https://github.com/bndtools/bnd/releases/tag/6.2.0
https://github.com/bjhargrave
This PGP key is the same used for verified commits on the GitHub release tag.
> Additional key for biz.aQute.bnd

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Bumped com.google.protobuf:protobuf-java to version 3.21.1, which has a new PGP key.
Signature resolves to "Sandy Zhang <sandyzhang@google.com>".
If dependabot makes a separate PR, this can be merged after the more descriptive dependabot commit.
> New key used on protobuf-java-3.21.1

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
I went back in time and found out when the keys for these projects changed.
> Update keys for liquibase and testcontainers

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "theodore rose <theodorerose@google.com>".
This extends and resolves the build error in PR #829
> New key used on protobuf-java-3.21.2

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Eclipse Angus Project <angus-dev@eclipse.org>".
This appears to be a new project at https://github.com/eclipse-ee4j/angus-activation
This adds the missing dependency for PR #785 and #824
> new key for org.eclipse.angus

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Scott Conway <scott@conwayfamily.name>".
The associated SourceForge user "sconway" is the publisher the associated release:
https://sourceforge.net/p/opencsv/source/ci/release5_6/tree/
https://sourceforge.net/u/sconway/profile/
This adds the missing dependency to resolve the build error of PR #820
> new key for com.opencsv

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "Joakim Erdfelt <joakime@apache.org>".
Signature matches ASF ID "joakime" published at https://people.apache.org/keys/committer/joakime
Unable to specifically associate the Apache ID with this Jetty project, but we are assured the artifact was published by an Apache member.
This extends and resolves the build error of PR #825
> Additional key for org.eclipse.jetty.websocket

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Signature resolves to "PayPal <DL-PP-Platform-Java-SDK@paypal.com>".
It is worth noting this project is deprecated per https://github.com/paypal/PayPal-Java-SDK
We do not anticipate any future releases of the project.
> new key for com.paypal.sdk

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
The oldest artifacts are unsigned.
The oldest signature resolves to "Maven Central Java.net import".  This key is already in the map for several other projects.
The next oldest artifacts are signed by "Stuart McCulloch (Sonatype) <mcculls@sonatype.com>".  This key is also already in the map for "org.sonatype.*"
The newest artfacts are signed by "Sam Berlin <sberlin@gmail.com>".  It is worth noting this matches the GitHub user of the recent releases:
https://github.com/cglib/cglib/releases/tag/RELEASE_3_3_0
https://github.com/sameb
> new keys for cglib:cglib

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
Oldest artifacts are signed by "Clifton Labs (maintainer) <davin.loegering@cliftonlabs.com>".
The signing key then changed to "Clifton Labs (Maven Maintainer) <davin.loegering@cliftonlabs.com>".
Finally, the most recent releases are signed by "Clifton Labs <davin.loegering@cliftonlabs.com>".
It is worth noting the project's GitHub: https://github.com/cliftonlabs/json-simple
> new key for com.github.cliftonlabs:json-simple

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
There are artifacts in the groupId org.apache.velocity.tools signed by the same keys.
> Wildcard groupId for org.apache.velocity.*

- resources/pgp-keys-map.list
- https://github.com/GPars/GPars/issues/62
>  org.codehaus.gpars:gpars:pom/jar:1.2.1 = noSig/noKey

- resources/pgp-keys-map.list
Key 0x09A808E1930F779CC6C54807E4C753D85335E876 is only deployed on pgp.mit.edu which has poor performance and generate many timeouts.
> Allow not found key for org.codehaus.plexus:plexus-archiver:4.5.0

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
New signature resolves to "Oracle Maven Release Key 2 <secalert_us@oracle.com>".
This does not match any documented MySQL signing key at https://dev.mysql.com/doc/refman/8.0/en/verifying-package-integrity.html
> mysql:mysql-connector-java relocated to com.mysql:mysql-connector-j

- resources/pgp-keys-map.list
Key: https://keyserver.ubuntu.com/pks/lookup?op=vindex&fingerprint=on&search=0x3C7C956B0ADCE8A006F392201E516D29843497DC
Release by: https://github.com/protocolbuffers/protobuf/releases/tag/v21.12
> Add new key for com.google.protobuf

- resources/pgp-keys-map.list
`org.springframework.integration:spring-integration-core:6.0.2` is signed with new key generated 2023-01-16
> Add new key for "Spring Builds"

- pgp-keys-map-test1/pom.xml
- resources/pgp-keys-map.list
- https://github.com/s4u/pgp-keys-map/pull/1742
- https://github.com/s4u/pgp-keys-map/pull/1743
-----
This is very strange case. I supposed that `jboss-logging` used in my project was very old and was missing signature due to that. But even the latest https://repo.maven.apache.org/maven2/org/jboss/logging/jboss-logging/3.5.3.Final/ (2023-07-06 00:34) are unsigned. 
https://central.sonatype.org/publish/requirements/#sign-files-with-gpgpgp
> *Sign Files with GPG/PGP*
> All files deployed need to be signed with GPG/PGP and a .asc file containing the signature must be included for each file. E.g. if you deploy the files
Apparently **must be included** can be relaxed for select ones...
> Declare jboss-logging to be not signed

- resources/pgp-keys-map.list
New key is present in https://downloads.apache.org/maven/KEYS.
> New key for org.apache.maven

- resources/pgp-keys-map.list
To help with (and similar in the group):
```
2024-05-05T08:24:18.8228097Z [ERROR] Not allowed artifact org.codehaus.modello:modello-plugin-converters:jar:2.4.0 and keyID:
2024-05-05T08:24:18.8230056Z 	org.codehaus.modello:modello-plugin-converters:2.4.0 = 0x84789D24DF77A32433CE1F079EB80E92EB2135B1
```
> Add keys used to sign the recent (incl. 2.4.0) modello releases

- pgp-keys-map-test2/pom.xml
- resources/pgp-keys-map.list
This also adds [the same] key for `CV`'s dependency - `commons-logging`.
> Add new key for commons-validator

- resources/pgp-keys-map.list
New key was used to create `org/eclipse/sisu/org.eclipse.sisu.plexus/0.9.0.M3/org.eclipse.sisu.plexus-0.9.0.M3.jar.asc`
This should help with:
- #2325
> Add new key for sisu

- resources/pgp-keys-map.list
New key was used to sign https://repo.maven.apache.org/maven2/org/hibernate/validator/hibernate-validator/8.0.2.Final/hibernate-validator-8.0.2.Final.jar
https://hibernate.org/community/keys/
> Add new key for org.hibernate.validator

- resources/pgp-keys-map.list
[1.10.0](https://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.10.0/) was signed by [0x2DB4F1EF0FA761ECC4EA935C86FDC7E2A11262CB](https://pgpkeys.eu/pks/lookup?search=0x2DB4F1EF0FA761ECC4EA935C86FDC7E2A11262CB&fingerprint=on&op=index)
> Add new key for commons-beanutils

- resources/pgp-keys-map.list
New key was used to create https://repo.maven.apache.org/maven2/org/xmlunit/xmlunit-core/2.10.1/xmlunit-core-2.10.1.jar.asc
Enables:
- #2976
> Add new key for org/xmlunit

- resources/pgp-keys-map.list
Once new spotbugs plugin is released and discovered by dependabot this
https://github.com/s4u/pgp-keys-map/blob/a8c07dd5b8b0306d5517838fc0acc2136c492d38/pgp-keys-map-test1/pom.xml#L1369-L1373
could fail to show that.
> Add new spotbugs key
